-- ================================================================
-- Supabase / PostgreSQL: tabla IoT datos_sensor + 100 datos ficticios
-- Basado en la arquitectura del archivo Backendless_IoT_Architecture.pptx
-- Periodo ficticio: 27-jul-2026 a 05-ago-2026 (10 registros por día)
-- Zona horaria de las lecturas: America/Guayaquil (UTC-05:00)
-- ================================================================

begin;

-- 1. Tabla principal de lecturas de sensores.
create table if not exists public.datos_sensor (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  temp numeric(5, 2) not null,
  presion numeric(7, 2) not null,
  humedad numeric(5, 2) not null,
  id_sensor smallint not null,

  constraint datos_sensor_temp_rango
    check (temp between -40.00 and 85.00),
  constraint datos_sensor_presion_rango
    check (presion between 300.00 and 1200.00),
  constraint datos_sensor_humedad_rango
    check (humedad between 0.00 and 100.00),
  constraint datos_sensor_id_sensor_positivo
    check (id_sensor > 0),
  constraint datos_sensor_sensor_fecha_unicos
    unique (id_sensor, created_at)
);

comment on table public.datos_sensor is
  'Lecturas meteorológicas recibidas desde sensores IoT ESP32/BME280.';

comment on column public.datos_sensor.temp is
  'Temperatura en grados Celsius.';
comment on column public.datos_sensor.presion is
  'Presión atmosférica en hectopascales (hPa).';
comment on column public.datos_sensor.humedad is
  'Humedad relativa en porcentaje.';

-- 2. Índices para consultas del dashboard por fecha y por sensor.
create index if not exists datos_sensor_created_at_idx
  on public.datos_sensor (created_at desc);

-- 3. Permisos explícitos para la API REST/GraphQL de Supabase.
-- En esta demostración, el ESP32 usa una clave publicable para insertar
-- y el dashboard puede consultar las lecturas sin iniciar sesión.
grant select, insert on table public.datos_sensor to anon, authenticated;
grant select, insert, update, delete on table public.datos_sensor to service_role;
grant usage, select on sequence public.datos_sensor_id_seq
  to anon, authenticated, service_role;

-- 4. Seguridad a nivel de filas (RLS).
alter table public.datos_sensor enable row level security;

drop policy if exists "lecturas visibles publicamente"
  on public.datos_sensor;

create policy "lecturas visibles publicamente"
  on public.datos_sensor
  for select
  to anon, authenticated
  using (true);

drop policy if exists "dispositivos pueden insertar lecturas"
  on public.datos_sensor;

create policy "dispositivos pueden insertar lecturas"
  on public.datos_sensor
  for insert
  to anon, authenticated
  with check (
    id_sensor > 0
    and created_at >= now() - interval '30 days'
    and created_at <= now() + interval '5 minutes'
  );

-- No se crean políticas UPDATE ni DELETE para anon/authenticated.
-- Por lo tanto, esos roles no pueden modificar ni borrar las lecturas.

-- 5. Carga de 100 lecturas ficticias.
-- Se generan 10 lecturas por día durante 10 días y se alternan 3 sensores.
-- ON CONFLICT evita duplicar estas lecturas si se vuelve a ejecutar el script.
with lecturas as (
  select
    n,
    timestamptz '2026-07-27 00:00:00-05'
      + ((n - 1) * interval '2 hours 24 minutes') as fecha_lectura,
    (1 + ((n - 1) % 3))::smallint as sensor
  from generate_series(1, 100) as serie(n)
)
insert into public.datos_sensor (
  created_at,
  temp,
  presion,
  humedad,
  id_sensor
)
select
  fecha_lectura,
  round((24 + 4 * sin(n * 0.42) + ((n % 5) - 2) * 0.18)::numeric, 2),
  round((1009 + 7 * cos(n * 0.19) + (n % 3) * 0.45)::numeric, 2),
  round((68 - 12 * sin(n * 0.31) + ((n % 7) - 3) * 0.35)::numeric, 2),
  sensor
from lecturas
on conflict (id_sensor, created_at) do nothing;

commit;

-- ================================================================
-- CONSULTAS DE VERIFICACIÓN
-- ================================================================

-- Debe devolver 100 en una tabla recién creada.
select count(*) as total_registros
from public.datos_sensor;

-- Debe mostrar 10 registros por día durante 10 días.
select
  (created_at at time zone 'America/Guayaquil')::date as dia,
  count(*) as registros
from public.datos_sensor
group by dia
order by dia;

-- Resumen de los valores generados.
select
  min(temp) as temp_min,
  max(temp) as temp_max,
  min(presion) as presion_min,
  max(presion) as presion_max,
  min(humedad) as humedad_min,
  max(humedad) as humedad_max
from public.datos_sensor;

-- Últimas 20 lecturas para el dashboard.
select id, created_at, temp, presion, humedad, id_sensor
from public.datos_sensor
order by created_at desc
limit 20;

-- NOTA DE PRODUCCIÓN:
-- Permitir INSERT al rol anon es práctico para una demostración, pero cualquier
-- persona que obtenga la clave publicable podría enviar datos falsos. Para un
-- despliegue real, autentique cada dispositivo mediante una Edge Function o un
-- servidor intermedio y retire INSERT de anon.
